package ch.bbbaden.m335.memories;

import com.codename1.components.SpanLabel;
import com.codename1.ext.filechooser.FileChooser;
import com.codename1.io.File;
import com.codename1.io.FileSystemStorage;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.io.MultipartRequest;
import com.codename1.io.NetworkManager;
import com.codename1.io.Util;
import com.codename1.ui.Button;
import com.codename1.ui.CN;
import static com.codename1.ui.CN.getCurrentForm;
import com.codename1.ui.CheckBox;
import com.codename1.ui.Image;
import com.codename1.ui.Toolbar;
import com.codename1.ui.layouts.BoxLayout;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStreamWriter;
import userclasses.StateMachine;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename
 * One</a> for the purpose of building native mobile applications using Java.
 */
public class MyApplication {

    private static Form current;

    public void init(Object context) {
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);
    }

    public void start() {
        if (current != null) {
            current.show();
            return;
        }
        new StateMachine("/theme");

//        Form hi = new Form("Hi World");
//        hi.setLayout(new BoxLayout(BoxLayout.Y_AXIS));
//        hi.addComponent(new Label("Hi World"));
//        
//        Button testImage = new Button("Browse Images");
//        testImage.addActionListener(e->{
//            if (FileChooser.isAvailable()) {
//                
//                FileChooser.showOpenDialog(".pdf,application/pdf,.gif,image/gif,.png,image/png,.jpg,image/jpg,.tif,image/tif,.jpeg,.bmp", e2-> {
//                    if(e2!=null && e2.getSource()!=null) {
//
//                        String file = (String)e2.getSource();
//                        try {
//                            Image img = Image.createImage(file);
//                            hi.add(new Label(img));
//                            if (true) return;
//                        } catch (Exception ex) {
//                            Log.e(ex);
//                        }
//                    }
//               });
//            }
//        });
//        hi.add(testImage);
//        hi.show();
    }

    public static Form getCurrent() {
        return current;
    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
        if (current != null) {
            current.show();
            return;
        }

    }

    public void destroy() {
    }
}
